#ifndef FI_DEFINITION_H
#define FI_DEFINITION_H

#define FI_D_MENU_HOME 0
#define FI_D_MENU_HOUR 1
#define FI_D_MENU_MINUTE 2
#define FI_D_MENU_SETTING 3
#define FI_D_MENU_QUARTERMIN 4
#define FI_D_MENU_PRECISION 5
#define FI_D_MENU_FLASH 6

#endif
